export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_OK = 'ADD_PRODUCT_OK'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const BEGIN_PRODUCTS_DOWNLOAD = 'BEGIN_PRODUCTS_DOWNLOAD'
export const PRODUCTS_DOWNLOAD_OK = 'PRODUCTS_DOWNLOAD_OK'
export const PRODUCTS_DOWNLOAD_ERROR = 'PRODUCTS_DOWNLOAD_ERROR'

export const RETRIEVE_PRODUCT_DELETE = 'RETRIEVE_PRODUCT_DELETE'
export const PRODUCT_DELETED_OK = 'PRODUCT_DELETED_OK'
export const PRODUCT_DELETED_ERROR = 'PRODUCT_DELETED_ERROR'

export const RETRIEVE_PRODUCT_EDIT= 'RETRIEVE_PRODUCT_EDITED'
export const BEGIN_EDIT_PRODUCT = 'BEGIN_EDIT_PRODUCT'
export const PRODUCT_EDITED_OK = 'PRODUCT_EDITED_OK'
export const PRODUCT_EDITED_ERROR = 'PRODUCT_EDITED_ERROR'

export const RETRIEVE_PRODUCT_BUY = 'RETRIEVE_PRODUCT_BUY'
export const PRODUCT_BUY_OK = 'PRODUCT_BUY_OK'
export const PRODUCT_BUY_ERROR = 'PRODUCT_BUY_ERROR'

export const BEGIN_PURCHASES_DOWNLOAD = 'BEGIN_PURCHASES_DOWNLOAD'
export const PURCHASES_DOWNLOAD_OK = 'PURCHASES_DOWNLOAD_OK'
export const PURCHASES_DOWNLOAD_ERROR = 'PURCHASES_DOWNLOAD_ERROR'
